function Hd = iir_chebyshev1_3400_44100
%IIR_CHEBYSHEV1_3400_44100 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 20-Apr-2024 18:17:34

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N      = 10;    % Order
Fpass1 = 300;   % First Passband Frequency
Fpass2 = 3400;  % Second Passband Frequency
Apass  = 3;     % Passband Ripple (dB)

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, Fs);
Hd = design(h, 'cheby1');

% [EOF]
